import { promises as fs } from "fs"
import path from "path"

const PUBLIC_DIR = path.join(process.cwd(), "public")

async function main() {
  const totalStart = performance.now()
  console.log("\n📁 Building static files...")

  await Promise.all([
    buildTypesetCSS(),
    buildRssXML(),
    buildRegistriesJSON(),
    buildSearchIndex(),
  ])

  const elapsed = ((performance.now() - totalStart) / 1000).toFixed(2)
  console.log(`\n✅ Static files built in ${elapsed}s!`)
}

async function buildTypesetCSS() {
  const typesetCssPath = path.join(PUBLIC_DIR, "typeset.css")

  const css = `/* Generated by build-static-files.mts */
/* This file replaces the previous dynamic route handler at app/typeset.css/route.ts */

/* Typeset CSS for documentation content */
.typeset-scroll {
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
}

.scroll-fade-x {
  position: relative;
}

.scrollbar-none {
  scrollbar-width: none;
  -ms-overflow-style: none;
}

.scrollbar-none::-webkit-scrollbar {
  display: none;
}

/* Code block styling */
[data-not-typeset] {
  font-feature-settings: normal;
  font-variation-settings: normal;
}

/* Typeset table styles */
.typeset-scroll table {
  width: 100%;
  border-collapse: collapse;
}
`

  await fs.mkdir(path.dirname(typesetCssPath), { recursive: true })
  await fs.writeFile(typesetCssPath, css)
  console.log("   ✅ public/typeset.css")
}

async function buildRssXML() {
  const rssPath = path.join(PUBLIC_DIR, "rss.xml")

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://ui.shadcn.com"
  const today = new Date().toUTCString()

  const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>shadcn/ui</title>
    <link>${appUrl}</link>
    <description>Beautifully designed components that you can copy and paste into your apps.</description>
    <language>en-us</language>
    <lastBuildDate>${today}</lastBuildDate>
    <atom:link href="${appUrl}/rss.xml" rel="self" type="application/rss+xml"/>
    <item>
      <title>shadcn/ui v4</title>
      <link>${appUrl}/docs</link>
      <description>Beautifully designed components that you can copy and paste into your apps.</description>
      <pubDate>${today}</pubDate>
    </item>
  </channel>
</rss>`

  await fs.mkdir(path.dirname(rssPath), { recursive: true })
  await fs.writeFile(rssPath, rss)
  console.log("   ✅ public/rss.xml")
}

async function buildRegistriesJSON() {
  const directoryPath = path.join(process.cwd(), "registry", "directory.json")
  const outputPath = path.join(PUBLIC_DIR, "r", "registries.json")

  let directory: Array<{ name: string; homepage: string; url: string; description?: string }> = []
  try {
    directory = JSON.parse(await fs.readFile(directoryPath, "utf8"))
  } catch {
    console.log("   ⚠️ registry/directory.json not found, using empty registries")
    directory = []
  }

  const registries = directory.map(
    ({ name, homepage, url, description }) => ({
      name,
      homepage,
      url,
      description,
    })
  )

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await fs.writeFile(outputPath, JSON.stringify(registries, null, 2))
  console.log("   ✅ public/r/registries.json")
}

async function buildSearchIndex() {
  const outputPath = path.join(PUBLIC_DIR, "r", "search-index.json")

  const searchIndex = {
    docs: [],
    components: [],
    version: 1,
    generatedAt: new Date().toISOString(),
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await fs.writeFile(outputPath, JSON.stringify(searchIndex, null, 2))
  console.log("   ✅ public/r/search-index.json")
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
